#!/usr/bin/env python3
"""Generates the checked-in ledger-archive capture fixture (fixtures/archive/capture.xdr).

The fixture is an ILLUSTRATIVE, truncated capture in the Slipstream capture XDR
subset (see crates/replay/src/xdr.rs). It is NOT real mainnet data; it models a
small sharded-counter workload over ledgers 100..=103 to exercise the replay
pipeline deterministically.
"""
import struct
import json

MAGIC = 0x534C5031
VERSION = 1


def pad4(n):
    return (4 - (n % 4)) % 4


def write_u32(buf, v):
    buf.extend(struct.pack(">I", v))


def write_bytes(buf, data):
    write_u32(buf, len(data))
    buf.extend(data)
    buf.extend(b"\x00" * pad4(len(data)))


def write_string(buf, s):
    write_bytes(buf, s.encode("utf-8"))


def write_key(buf, ktype, f1, f2=""):
    write_u32(buf, ktype)
    write_string(buf, f1)
    write_string(buf, f2)


def write_record(buf, tx_hash, source, ro, rw):
    buf.extend(tx_hash)
    buf.extend(b"\x00" * pad4(len(tx_hash)))
    write_string(buf, source)
    write_u32(buf, len(ro))
    for k in ro:
        write_key(buf, *k)
    write_u32(buf, len(rw))
    for k in rw:
        write_key(buf, *k)


def main():
    C = "C0000000000000000000000000000000000000000000000000000000000000001"  # contract
    A1 = "G0000000000000000000000000000000000000000000000000000000000000001"
    A2 = "G0000000000000000000000000000000000000000000000000000000000000002"
    A3 = "G0000000000000000000000000000000000000000000000000000000000000003"

    recs = [
        # Tx 1: shard:0 write, reads shared state.
        ([0x11] * 32, A1, [(2, C, "state")], [(2, C, "shard:0")]),
        # Tx 2: shard:1 write, reads shared state.
        ([0x22] * 32, A2, [(2, C, "state")], [(2, C, "shard:1")]),
        # Tx 3: reads two shards and the shared state, no writes.
        ([0x33] * 32, A3, [(2, C, "state"), (2, C, "shard:0"), (2, C, "shard:1")], []),
    ]

    buf = bytearray()
    write_u32(buf, MAGIC)
    write_u32(buf, VERSION)
    write_u32(buf, 100)   # from_ledger
    write_u32(buf, 103)   # to_ledger
    write_u32(buf, 4)     # checkpoint_count
    write_u32(buf, len(recs))
    for tx_hash, source, ro, rw in recs:
        write_record(buf, tx_hash, source, ro, rw)

    path = "fixtures/archive/capture.xdr"
    with open(path, "wb") as f:
        f.write(bytes(buf))

    manifest = {
        "captured_from": (
            "illustrative fixture: synthetic sharded-counter capture over "
            "ledgers 100..=103. Generated by tools/gen_capture_fixture.py. "
            "Not measured mainnet data; used for conformance and determinism testing."
        ),
        "format": "slipstream-capture-xdr",
        "version": VERSION,
        "from_ledger": 100,
        "to_ledger": 103,
        "checkpoint_count": 4,
        "byte_size": len(buf),
    }
    with open("fixtures/archive/manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")

    print(f"wrote {path} ({len(buf)} bytes) and fixtures/archive/manifest.json")


if __name__ == "__main__":
    main()
